### ISSUE TITLE
Keep aspect ratio and skipping smaller images during resize

### ISSUE THREAD

**Issue by jamabaiz** [biellSilva/python-webp#1]
Hi,
I came across your library but needed to make a few adjustments myself. By default, it doesn't keep the aspect ratio and doesn't skip images that are smaller than the expected size.

I've attached the sample code I use below.
It could probably be implemented with additional flags, such as `--keep-aspect-ratio` (or `--ignore-aspect-ratio`) and `--skip-smaller-size`.

```
    def resize_image(self, image: ImageType) -> ImageType:
        if self.size:
            if(image.size[0] < self.size[0] and image.size[1] < self.size[1]):
                self.__log(f"Skipping resize to {self.__size_to_string(self.size)}, image is smaller {self.__size_to_string(image.size)}")
                return image

            self.__log(f"Resizing image to {self.__size_to_string(self.size)}")
            if(image.size[0]>image.size[1]):
                factor=self.size[0]/image.size[0]
            else:
                factor=self.size[1]/image.size[1]
            new_width = round(image.size[0] * factor)
            new_height = round(image.size[1] * factor)
            return image.resize(size=(new_width, new_height), resample=Image.LANCZOS)
        return image
```

**Comment by biellSilva** [comment]
I've fixed it and added those features on v2.0.0, you can check that on [PyPi](https://pypi.org/project/python-webp/)
sorry for the delay to fix it, I haven't noticed your issues before today's afternoon
