### ISSUE TITLE
Images are converted sequentially

### ISSUE THREAD

**Issue by jamabaiz** [biellSilva/python-webp#2]
There if issue with multithread. Photos are converted almost sequentially.
The reason is that: for each file in loop, is created new `ThreadPoolExecutor`

```py
 with ThreadPoolExecutor(max_workers=self.threads) as executor:
```

Should be placed before 
```py
for file in Path(path).iterdir():
```

... or better, create single variable in constructor of class `Core`, then need to call `executor.shudown(wait=True)` , after first process_images execution.

**Comment by biellSilva** [comment]
your issue has been fixed with the new release
thanks to reporting that and helping me to improve the project
